### ISSUE TITLE
Unable to read register

### ISSUE THREAD

**Issue by 654955321** [trackle-iot/trackle-modbus-esp-idf#1]
`#include <Arduino.h>
#include "ModbusClientRTU.h"

#define RXPIN GPIO_NUM_15
#define TXPIN GPIO_NUM_16

uint16_t Distance;

#define modbus_address_1 0x01 
#define PV 0x0100                  

ModbusClientRTU MB(Serial2);

void handleData(ModbusMessage response, uint32_t token)
{
  uint16_t offset1 = 3;

  if (response.getServerID() == modbus_address_1)
  {
    offset1 = response.get(offset1, Distance);
    Serial.printf("Real-time distance: %d mm\r\n", Distance); 
  }
}

void setup()
{
  Serial.begin(115200);
  Serial2.begin(115200, SERIAL_8N1, TXPIN, RXPIN);
  MB.onDataHandler(&handleData); 
  MB.setTimeout(2000);         
  MB.begin(Serial2);          
}

void loop()
{
  uint32_t Token = 1111;
  Error err;
  err = MB.addRequest(Token++, modbus_address_1, READ_HOLD_REGISTER, PV, 0x0001);
  delay(1000);
}
`
The above is the code for my Arduino, which uses an e-modbus library and reads register values normally.

`#include "trackle_modbus.h"
#include <esp_log.h>

void app_main()
{
    ModbusError res;

    // Initialize and start Modbus controller
    modbus_config_t modbus_config = {
        .uart_num = UART_NUM_1,
        .baud_rate = 115200,        .data_bits = UART_DATA_8_BITS,
        .parity = UART_PARITY_DISABLE,
        .stop_bits = UART_STOP_BITS_1,
        .tx_io_num = 16,
        .rx_io_num = 15,
        .rts_io_num = UART_PIN_NO_CHANGE,
        .cts_io_num = UART_PIN_NO_CHANGE,
        .mode = UART_MODE_UART,
    };

    Trackle_Modbus_init(&modbus_config);
    Trackle_Modbus_set_timeout(250);
    vTaskDelay(1000 / portTICK_PERIOD_MS);

    uint16_t result[10];
    // uint16_t write[10];

    while (1)
    {
        ESP_LOGI("main", "------------");
        ESP_LOGI("main", "T_READ_HOLDING_REGISTERS");
        res = Trackle_Modbus_execute_command(T_READ_HOLDING_REGISTERS, 1, 100, 1, &result);
        ESP_LOGI("main", "Function %d, res %d, value %d", T_READ_HOLDING_REGISTERS, res, result[0]);
        vTaskDelay(1000 / portTICK_PERIOD_MS);
        ESP_LOGI("main", "");

        // write[0] = 200;
        // ESP_LOGI("main", "------------");
        // ESP_LOGI("main", "T_WRITE_SINGLE_REGISTER");
        // res = Trackle_Modbus_execute_command(T_WRITE_SINGLE_REGISTER, 1, 231, 1, &write);
        // ESP_LOGI("main", "Function %d, res %d", T_WRITE_SINGLE_REGISTER, res);
        // vTaskDelay(1000 / portTICK_PERIOD_MS);
        // ESP_LOGI("main", "");

        /*write[0] = 200;
        ESP_LOGI("main", "------------");
        ESP_LOGI("main", "T_WRITE_MULTIPLE_REGISTERS");
        res = modbus_execute_command(T_WRITE_MULTIPLE_REGISTERS, 1, 231, 1, &write);
        ESP_LOGI("main", "Function %d, res %d", T_WRITE_MULTIPLE_REGISTERS, res);
        vTaskDelay(1000 / portTICK_PERIOD_MS);
        ESP_LOGI("main", "");*/
    }
}`
This is a change from your library, and I don't know where the parameters were set incorrectly, so it cannot function properly. Please help me solve it. Thank you very much.

**Comment by flaz83** [comment]
Hi, 
which error do you have? please check register number you are trying to read.
In Arduino code you are reading register address 0x0100, with trackle_modbus you are reading address 100.
Try this:
`res = Trackle_Modbus_execute_command(T_READ_HOLDING_REGISTERS, 1, 0x100, 1, &result);`

**Comment by 654955321** [comment]
Thank you for your prompt. After the address change, it has been functioning normally.
